#!/bin/bash

#PBS -q hugemem
#PBS -l walltime=48:00:00
#PBS -l storage=gdata/er4+scratch/er4+scratch/eg3+gdata/eg3
#PBS -N job_hugemem_mrnbc
#PBS -P er4
#PBS -l ncpus=26
#PBS -l mem=1440gb
#PBS -l wd

gcm=CNRM-CM5
rcp=rcp45
per=bc_fut
scale=awap

source /g/data/er4/jr6311/miniconda/bin/activate isimip

cd ../
python3 text_nc_converter.py \
    --model_id ${gcm} \
    --rcp ${rcp} \
    --time_period ${per} \
    --scale ${scale}
